### ISSUE TITLE
Config Parser Issue

### ISSUE THREAD

**Issue by hotdog218** [ejach/tautulliToLetterboxd#39]
Hi, I've used your script in the past and not run into any issues, but now I can't seem to get around this config parser issue:

```
python tautulli_to_letterboxd.py -u UserName

Traceback (most recent call last):
  File "tautulli_to_letterboxd.py", line 37, in <module>
    BASE_URL = CFG['HOST']['base_url'] + '/api/v2'
  File "C:\Users\Zach\AppData\Local\Programs\Python\Python37-32\lib\configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'HOST'
```

Config looks like this:
```
[HOST]
# The Tautulli host
# Default: http://localhost:8181
baseurl=http://192.168.1.7:8181
[AUTH]
# Tautulli API token
# Found in Settings > Web Interface > API Key
token=XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

I don't really think I've changed anything since the last time I ran the script. Any insight as to what's happening?

Appreciate any help you can give!

**Comment by hotdog218** [comment]
Hi, thanks for the quick response!

1. I just updated to the latest version of Python (3.10) and tried cloning and running it again, but unfortunately ran into the same error (with a little extra):
```
python -m tautulli_to_letterboxd -u UserName

Traceback (most recent call last):
  File "C:\Users\Zach\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Zach\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Projects\Temp\Taut2LBXMk2\tautulliToLetterboxd\tautulli_to_letterboxd\__main__.py", line 1, in <module>
    from tautulli_to_letterboxd.tautulli_to_letterboxd import main
  File "D:\Projects\Temp\Taut2LBXMk2\tautulliToLetterboxd\tautulli_to_letterboxd\tautulli_to_letterboxd.py", line 37, in <module>
    BASE_URL = CFG['HOST']['base_url'] + '/api/v2'
  File "C:\Users\Zach\AppData\Local\Programs\Python\Python310\lib\configparser.py", line 1258, in __getitem__
    raise KeyError(key)
KeyError: 'base_url'
```
2. Originally tried it with Python 3.7, now using Python 3.10.
3. Unfortunately this didn't help much- See bullet point 1.

I also verified that http://192.168.1.7:8181/api/v2 is accessible from my machine, and just for fun tried generating a new API key in Tautulli to no avail. Any other suggestions?

**Comment by hotdog218** [comment]
So, I'm not sure how to fix the problem originally, but I replaced the BASE_URL variable directly with my tautulli URL and it worked.
```
# BASE_URL = CFG['HOST']['base_url'] + '/api/v2'
BASE_URL = 'http://192.168.1.7:8181/api/v2'
```
I'm not sure if this is a problem for everybody or just me, but if it's limited to my machine feel free to close this issue.

**Comment by ejach** [comment]
Thank you for correcting this issue, glad it got resolved!
